---
abstract: "Japanese mobile phone's pictogram operator"
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom aaaatttt@ gmail dotottto commmmmE<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-MobileJPPictogram
no_index:
  directory:
    - inc
    - t
provides:
  Template::Plugin::MobileJPPictogram:
    file: lib/Template/Plugin/MobileJPPictogram.pm
    version: 0.06
requires:
  Encode::JP::Mobile: 0
  Encode::JP::Mobile::Charnames: 0
  Filter::Util::Call: 0
  Template: 0
  perl: 5.008008
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
