---
abstract: 'Japanese mobile phone''s pictogram operator'
author:
  - 'Tokuhiro Matsuno <tokuhirom aaaatttt gmail dotottto commmmm>'
build_requires:
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Template-Plugin-MobileJPPictogram
no_index:
  directory:
    - inc
    - t
requires:
  Encode::JP::Mobile: 0
  Encode::JP::Mobile::Charnames: 0
  Template: 0
version: 0.02
